<a href="https://colab.research.google.com/github/Adnan-Imam0/datascience_and_ai/blob/main/notebooks/Maths/sec3_linearAlgebraFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Fundamentals

In [40]:
import numpy as np

## Create Vectors and Matrices using Numpy

In [41]:
# create matrixes
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [42]:
# Addition
print("Addintion: \n", A + B)

Addintion: 
 [[ 6  8]
 [10 12]]


In [43]:
# Subtraction
print("Subtraction: \n", B-A)

Subtraction: 
 [[4 4]
 [4 4]]


In [44]:
# Scalar Multiplications
print("Scalar Multiplication: \n", 2*A)

Scalar Multiplication: 
 [[2 4]
 [6 8]]


## Implement Matrix-vector Multiplications

In [45]:
# matrix and vector creation
M = np.array([[1,2,3], [4,5, 6], [7,8,9]])
v = np.array([1, 0, -1])

In [46]:
# matrix-vector multiplications
result = np.dot(M, v)
print(result)

[-2 -2 -2]


## Explore Special Matrices

In [47]:
# Identity Matrix
I = np.eye(3)
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("A X I \n", np.dot(A , I))

A X I 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [48]:
# Diagonal and Zero Matrix
D = np.diag([1,2,3])
Z = np.zeros((3,3))
print("Diagonal \n", D)
print("Zero Matrix \n", Z)


Diagonal 
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Zero Matrix 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Calculate the Determinant and Inverse

In [49]:
# Define a 2x2 matrix
matrix_2x2 = np.array([[4, 7], [2, 6]])

# Calculate the determinant
determinant = np.linalg.det(matrix_2x2)
print("Determinant of the 2x2 matrix: \n", determinant)

# Calculate the inverse (if the determinant is non-zero)
try:
    inverse_matrix = np.linalg.inv(matrix_2x2)
    print("Inverse of the 2x2 matrix: \n", inverse_matrix)
except np.linalg.LinAlgError:
    print("The matrix is singular and does not have an inverse.")

Determinant of the 2x2 matrix: 
 10.000000000000002
Inverse of the 2x2 matrix: 
 [[ 0.6 -0.7]
 [-0.2  0.4]]


# Task
Compute the determinant and inverse of a 2x2 matrix using NumPy, verify properties of matrix multiplication using NumPy, and explain the verified properties.

## Define matrices

### Subtask:
Create suitable matrices in a code cell to demonstrate the properties of matrix multiplication.


**Reasoning**:
The subtask requires creating compatible matrices and a scalar for demonstrating matrix multiplication properties. This can be done by defining NumPy arrays for the matrices and a Python variable for the scalar in a single code cell.



In [50]:
# Define three compatible matrices for multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.array([[9, 10], [11, 12]])

# Define a scalar value
k = 2

## Verify associativity

### Subtask:
Write code to show that for matrices A, B, and C, (AB)C = A(BC).


**Reasoning**:
Write code to calculate (AB)C and A(BC) and compare them.



In [51]:
# Calculate (AB)C
left_side = np.dot(np.dot(A, B), C)

# Calculate A(BC)
right_side = np.dot(A, np.dot(B, C))

# Print both sides
print("(AB)C:\n", left_side)
print("\nA(BC):\n", right_side)

# Compare the results
are_equal = np.array_equal(left_side, right_side)
print("\nAre (AB)C and A(BC) equal?", are_equal)

(AB)C:
 [[ 413  454]
 [ 937 1030]]

A(BC):
 [[ 413  454]
 [ 937 1030]]

Are (AB)C and A(BC) equal? True


## Verify distributivity

### Subtask:
Write code to show that for matrices A, B, and C, A(B + C) = AB + AC and (A + B)C = AC + BC.


**Reasoning**:
Calculate and compare both sides of the distributive properties using the previously defined matrices A, B, and C.



In [52]:
# Calculate A(B + C)
left_dist_1 = np.dot(A, B + C)

# Calculate AB + AC
right_dist_1 = np.dot(A, B) + np.dot(A, C)

# Print both sides of the first distributive property
print("A(B + C):\n", left_dist_1)
print("\nAB + AC:\n", right_dist_1)

# Compare the results of the first distributive property
are_equal_dist_1 = np.array_equal(left_dist_1, right_dist_1)
print("\nAre A(B + C) and AB + AC equal?", are_equal_dist_1)

# Calculate (A + B)C
left_dist_2 = np.dot(A + B, C)

# Calculate AC + BC
right_dist_2 = np.dot(A, C) + np.dot(B, C)

# Print both sides of the second distributive property
print("\n(A + B)C:\n", left_dist_2)
print("\nAC + BC:\n", right_dist_2)

# Compare the results of the second distributive property
are_equal_dist_2 = np.array_equal(left_dist_2, right_dist_2)
print("\nAre (A + B)C and AC + BC equal?", are_equal_dist_2)

A(B + C):
 [[ 50  56]
 [114 128]]

AB + AC:
 [[ 50  56]
 [114 128]]

Are A(B + C) and AB + AC equal? True

(A + B)C:
 [[142 156]
 [222 244]]

AC + BC:
 [[142 156]
 [222 244]]

Are (A + B)C and AC + BC equal? True


## Verify scalar multiplication property

### Subtask:
Write code to show that for a scalar k and matrices A and B, k(AB) = (kA)B = A(kB).


**Reasoning**:
The instructions require calculating and comparing three expressions involving scalar and matrix multiplication. This can be done in a single code block using NumPy's broadcasting and matrix multiplication capabilities, followed by printing and comparing the results as requested.



In [53]:
# Calculate k * (A @ B)
result_k_AB = k * np.dot(A, B)
print("k * (A @ B):\n", result_k_AB)

# Calculate (k * A) @ B
result_kA_B = np.dot(k * A, B)
print("\n(k * A) @ B:\n", result_kA_B)

# Calculate A @ (k * B)
result_A_kB = np.dot(A, k * B)
print("\nA @ (k * B):\n", result_A_kB)

# Compare the results of k * (A @ B) and (k * A) @ B
are_equal_1 = np.array_equal(result_k_AB, result_kA_B)
print("\nAre k * (A @ B) and (k * A) @ B equal?", are_equal_1)

# Compare the results of k * (A @ B) and A @ (k * B)
are_equal_2 = np.array_equal(result_k_AB, result_A_kB)
print("\nAre k * (A @ B) and A @ (k * B) equal?", are_equal_2)

k * (A @ B):
 [[ 38  44]
 [ 86 100]]

(k * A) @ B:
 [[ 38  44]
 [ 86 100]]

A @ (k * B):
 [[ 38  44]
 [ 86 100]]

Are k * (A @ B) and (k * A) @ B equal? True

Are k * (A @ B) and A @ (k * B) equal? True


## Verify identity property

### Subtask:
Write code to show that for a matrix A and identity matrix I, AI = IA = A.


**Reasoning**:
Write code to create a 2x2 identity matrix, perform matrix multiplication with matrix A, print the results, and verify if the results are equal to A.



In [54]:
# Create a 2x2 identity matrix
I = np.eye(2)
print("Identity Matrix (I):\n", I)

# Calculate A * I
result_AI = np.dot(A, I)
print("\nA * I:\n", result_AI)

# Calculate I * A
result_IA = np.dot(I, A)
print("\nI * A:\n", result_IA)

# Verify AI = A
are_equal_AI_A = np.array_equal(result_AI, A)
print("\nIs A * I equal to A?", are_equal_AI_A)

# Verify IA = A
are_equal_IA_A = np.array_equal(result_IA, A)
print("Is I * A equal to A?", are_equal_IA_A)

Identity Matrix (I):
 [[1. 0.]
 [0. 1.]]

A * I:
 [[1. 2.]
 [3. 4.]]

I * A:
 [[1. 2.]
 [3. 4.]]

Is A * I equal to A? True
Is I * A equal to A? True


## Explain properties

### Subtask:
Provide a markdown cell explaining each of the verified properties of matrix multiplication.


**Reasoning**:
Create a markdown cell to explain the verified properties of matrix multiplication.



**Reasoning**:
The previous command failed because markdown content was placed inside a code block. I need to create a markdown cell and put the explanation there.



In [55]:
# This is a placeholder cell to ensure the markdown cell is created next.
# The actual markdown content will be in the following markdown cell.
pass

**Reasoning**:
Create a markdown cell with the explanation of the matrix multiplication properties as requested in the subtask instructions.



In [56]:
%%markdown
## Properties of Matrix Multiplication

Through the code executed, we have empirically verified several key properties of matrix multiplication using NumPy:

### Associativity: (AB)C = A(BC)
This property states that when multiplying three or more matrices, the grouping of the matrices does not affect the final product. As demonstrated by the code, multiplying the result of AB by C yields the same matrix as multiplying A by the result of BC.

### Distributivity: A(B + C) = AB + AC and (A + B)C = AC + BC
Matrix multiplication is distributive over matrix addition. The first property, A(B + C) = AB + AC, shows that multiplying a matrix A by the sum of matrices B and C is equivalent to adding the products of A and B, and A and C. Similarly, the second property, (A + B)C = AC + BC, shows that multiplying the sum of matrices A and B by matrix C is equivalent to adding the products of A and C, and B and C. Our code has shown that both of these equalities hold true.

### Scalar Multiplication: k(AB) = (kA)B = A(kB)
This property illustrates how scalar multiplication interacts with matrix multiplication. Multiplying a scalar k by the product of matrices A and B gives the same result as multiplying the scalar k by matrix A first and then multiplying by matrix B, or multiplying matrix A by the scalar k times matrix B. The code execution confirmed that all three expressions result in the same matrix.

### Identity Property: AI = IA = A
The identity matrix, denoted by I, plays a role similar to the number 1 in scalar multiplication. When a matrix A is multiplied by the identity matrix I (of compatible dimensions), the result is the original matrix A, regardless of the order of multiplication (AI or IA). Our code successfully demonstrated that multiplying matrix A by the identity matrix I in either order results in matrix A itself.

## Properties of Matrix Multiplication

Through the code executed, we have empirically verified several key properties of matrix multiplication using NumPy:

### Associativity: (AB)C = A(BC)
This property states that when multiplying three or more matrices, the grouping of the matrices does not affect the final product. As demonstrated by the code, multiplying the result of AB by C yields the same matrix as multiplying A by the result of BC.

### Distributivity: A(B + C) = AB + AC and (A + B)C = AC + BC
Matrix multiplication is distributive over matrix addition. The first property, A(B + C) = AB + AC, shows that multiplying a matrix A by the sum of matrices B and C is equivalent to adding the products of A and B, and A and C. Similarly, the second property, (A + B)C = AC + BC, shows that multiplying the sum of matrices A and B by matrix C is equivalent to adding the products of A and C, and B and C. Our code has shown that both of these equalities hold true.

### Scalar Multiplication: k(AB) = (kA)B = A(kB)
This property illustrates how scalar multiplication interacts with matrix multiplication. Multiplying a scalar k by the product of matrices A and B gives the same result as multiplying the scalar k by matrix A first and then multiplying by matrix B, or multiplying matrix A by the scalar k times matrix B. The code execution confirmed that all three expressions result in the same matrix.

### Identity Property: AI = IA = A
The identity matrix, denoted by I, plays a role similar to the number 1 in scalar multiplication. When a matrix A is multiplied by the identity matrix I (of compatible dimensions), the result is the original matrix A, regardless of the order of multiplication (AI or IA). Our code successfully demonstrated that multiplying matrix A by the identity matrix I in either order results in matrix A itself.


## Summary:

### Data Analysis Key Findings

*   The associativity property of matrix multiplication, (AB)C = A(BC), was successfully verified using NumPy for the given matrices A, B, and C.
*   Both distributive properties of matrix multiplication over addition, A(B + C) = AB + AC and (A + B)C = AC + BC, were confirmed to hold true for the given matrices.
*   The scalar multiplication property, k(AB) = (kA)B = A(kB), was demonstrated to be valid for the specified scalar k and matrices A and B.
*   The identity property of matrix multiplication, AI = IA = A, was verified for the given matrix A and the corresponding identity matrix I.
*   A markdown explanation detailing each verified property (Associativity, Distributivity, Scalar Multiplication, and Identity Property) was successfully generated.

### Insights or Next Steps

*   These verified properties are fundamental to matrix algebra and linear transformations, highlighting how matrix operations behave similarly to scalar arithmetic in some aspects, while also having unique characteristics (like non-commutativity in general).
*   Future steps could involve exploring other matrix properties, such as the non-commutativity of matrix multiplication (AB != BA in general) or the properties of the transpose or inverse of a matrix.


## Create a Block Diagonal Matrix

In [57]:
from scipy.linalg import block_diag
import numpy as np

# Define some matrices (blocks)
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])
C = np.array([[14]])

# Create the block diagonal matrix
block_diagonal_matrix = block_diag(A, B, C)

# Print the resulting matrix
print("Block Diagonal Matrix:\n", block_diagonal_matrix)

Block Diagonal Matrix:
 [[ 1  2  0  0  0  0]
 [ 3  4  0  0  0  0]
 [ 0  0  5  6  7  0]
 [ 0  0  8  9 10  0]
 [ 0  0 11 12 13  0]
 [ 0  0  0  0  0 14]]
